### ISSUE TITLE
Open clicked date in macOS Calendar app

### ISSUE THREAD

**Issue by mzdr** [mzdr/timestamp#11]
Clicking on a date should open the native macOS Calendar app with the clicked date preselected. Also provide an option to turn off this behaviour.

Tasks:
- [x] ClickHandler w/ AppleScript 
- [x] Preferences option to turn it off

**Comment by charlex** [comment]
This would be a cool feature. Is it supposed to work? It doesn't seem to be working for me. 

Thanks for the great app!

**Comment by mzdr** [comment]
Hey @charlex,

I’ve already implemented it but it’s not released yet. It will be shipped with [v1.1.0](https://github.com/mzdr/timestamp/milestone/3), which hopefully will come soon. 😊
