### ISSUE TITLE
Improve documentation/website on how to customize it

### ISSUE THREAD

**Issue by zeke** [mzdr/timestamp#12]
Congrats on your first Electron app! I see this in the README:

> customizable date/time display

But I don't see how to customize anything. Is that enabled yet?

**Comment by mzdr** [comment]
Hi Zeke!

Thanks and thank you for asking! The preferences window is hidden in a right-click menu under the tray "icon" (date/time display in our case). Have you tried that? Is that what you are referring to?

Nevertheless this is something that's missing in the documentation and I will improve that!

**Comment by zeke** [comment]
Ah! That works. Would be cool if the preferences pane had a link to the momentjs reference.

**Comment by mzdr** [comment]
The Help-Button next to the clock format input field links to the Moment.js documentation. 😊

**Comment by zeke** [comment]
facepalm. Thanks!
