### ISSUE TITLE
publish to brew cask

### ISSUE THREAD

**Issue by ZakariaRidouh** [mzdr/timestamp#14]
it would be great to make this application installable through brew cask to make it much easier to manage.

cheers!
😄

**Comment by amilajack** [comment]
This would be great! +1

**Comment by mzdr** [comment]
I'm on it!

**Comment by mzdr** [comment]
It's pending! caskroom/homebrew-cask#24837 👍  😃

**Comment by mzdr** [comment]
Done! 

@ZakariaRidouh Thanks for suggesting!
