### ISSUE TITLE
PR: Spectron Support

### ISSUE THREAD

**Issue by amilajack** [mzdr/timestamp#15]
Willing to add some initial spectrum support. Would a PR for that be welcome?

**Comment by mzdr** [comment]
Hey Amila!

That would be awesome! I think I would learn a lot from it too, so go for it! 

I'm currently redesigning the flow of the app, meaning I'm dropping the right-click context menu and rebuild everything with web components. I hope this doesn't interfere with your upcoming additions, but I guess not. 😄  

Thanks for your support!

**Comment by amilajack** [comment]
There is a possibility that the changes will conflict. How about I make the PR after your changes?

**Comment by mzdr** [comment]
Sounds good! I'll keep you posted!

**Comment by mzdr** [comment]
I started working on this app again and currently I’m cleaning up old/stale issues. I will get in touch if necessary.
