### ISSUE TITLE
Won't start at startup

### ISSUE THREAD

**Issue by AzkaarAli** [mzdr/timestamp#17]
I have checked the "Start at Login" in the Preferences but it won't start automatically.

**Comment by mzdr** [comment]
Hey there!

Thanks for reporting! Which version of OSX/macOS are you running on? Also could you check, when you have enabled "Start at Login", if there is an entry in your `System Preferences` under `Users & Groups` → `Login Items` ?

![image](https://cloud.githubusercontent.com/assets/3847901/20920616/ef76d98a-bba0-11e6-92e1-017d5ed6556e.png)

**Comment by AzkaarAli** [comment]
Thank you for reply!

I am running madOS Sierra Version 10.12.1
It is also there in my System Preferences under Users & Groups → Login Items as you can see in attached image.
![image](https://cloud.githubusercontent.com/assets/3090215/21258310/35e472ba-c39e-11e6-861e-a858babaacca.png)


Also, is there a way I could run 2 instances of TimeStamp. I want 1 with my local time and other with (my local hour - 9). Is this possible?

**Comment by mzdr** [comment]
Hey there!

At first I thought this might be an issue with macOS Sierra but it's not. Have you (accidentally) moved the Timestamp application after you've enabled `Start at Login`? This would explain why there is no logo and this warning icon.

Try to disable and re-enable the `Start at Login` checkbox and check the `System Preferences` again if there is the correct logo and the warning icon has gone.

Regarding your question about multiple instances, there is theoretically a way to achieve this. From the official Electron [docs](http://electron.atom.io/docs/api/app/#appmakesingleinstancecallback):

> On macOS the system enforces single instance automatically when users try to open a second instance of your app in Finder, and the open-file and open-url events will be emitted for that. However when users start your app in command line the system’s single instance mechanism will be bypassed[…]

This also means that multiple Timestamp instances would currently share the _same_ settings. I could implement a command line parameter that gives you the ability to define the name of the settings file and therefore you can start Timestamp with _separate_ settings. 

Feel free to open another issue with this feature request and I'll have a look into it. 👍

**Comment by AzkaarAli** [comment]
Hi,

I did disable and re-enable thing and Icon starts showing but it still won't start after restart.
![screen shot 2017-01-11 at 2 35 55 pm](https://cloud.githubusercontent.com/assets/3090215/21843100/852e143a-d80b-11e6-8228-979494807efc.png)

**Comment by mzdr** [comment]
Please try again with 1.1.0 which will be released soon. If this bug is still there please reopen this ticket or reply here.
