### ISSUE TITLE
gap on left side of clock

### ISSUE THREAD

**Issue by robjtede** [mzdr/timestamp#18]
Not necessarily something that needs changing in the repo but I'd like to get rid of it just for myself and not sure what to change

**Comment by mzdr** [comment]
Hey there!

Thanks for reporting! Unfortunately this is something that annoys me as well but there's nothing I can do about it. I already created an issue (#2) back then when I stumbled upon this problem. Currently Electron doesn't support to set a tray without an icon.

I'm sorry but you can be sure that I'll immediately implement it as soon as it's possible.
