### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by tgottc** [mzdr/timestamp#19]
Hello. It's the most beautiful calendar I've found for the menu bar, thanks.
However, I believe it is out of alignment -- too low and there is a large space on the left:
<img width="311" alt="screen shot 2017-01-23 at 22 30 53" src="https://cloud.githubusercontent.com/assets/11369395/22228963/c4ee8d66-e1bb-11e6-8133-300d3cffd848.png">
I'm on Sierra 10.12.2.

**Comment by mzdr** [comment]
Hi @tgottc,

thanks for reporting! Regarding the large space I unfortunately can't do anything about it (right now). See this bug report at the official electron repository: https://github.com/electron/electron/issues/5439

Regarding the "low hanging" time I'll look into it and get back to you asap.

**Comment by kevinschaich** [comment]
+1, still an issue and looks like the Electron bug has since been resolved

**Comment by mzdr** [comment]
Should be fixed in 1.1.0. Do you want to test a release candidate? If not release should be soon.
