### ISSUE TITLE
Use canvas to fake tray label as icon

### ISSUE THREAD

**Issue by mzdr** [mzdr/timestamp#2]
Since Electron doesn't provide a way to have a tray without an icon (see [electron/issues/1553](https://github.com/electron/electron/issues/1553) and even with an empty image as icon, there still is this empty gap), there could be a chance to achieve the same effect with using the icon as the actual label.

See [electron/issues/5439](https://github.com/electron/electron/issues/5439)

**Comment by Jackymancs4** [comment]
Hello, I've succefully implemeted this feature, and it works quite well.
This is the original app, version 1.0.1 with ddd DD MM YY - HH:mm:ss format:
<img width="227" alt="schermata 2017-12-04 alle 12 35 47" src="https://user-images.githubusercontent.com/6209647/33551205-e4c05c5a-d8f0-11e7-89d6-06a06c175bf7.png">

and this is it using the canvas icon:
<img width="203" alt="schermata 2017-12-04 alle 12 35 11" src="https://user-images.githubusercontent.com/6209647/33551204-e49cc128-d8f0-11e7-9982-79418ee49563.png">
(yes, the margins are adjustable)

Right now I've failed to catch the right macOS system font SanFrancisco, but it's still a work in progress.
Would you be willing to review a PR?

The code works on both the branch master and develop

**Comment by mzdr** [comment]
Hey @Jackymancs4,

this sounds awesome! I remember that I once tried to implement it but I had troubles with it when it was repainting/updating. I would love to review a PR. Go for it!

**Comment by Jackymancs4** [comment]
Hello @mzdr,

have you taken a look at my PR?

**Comment by mzdr** [comment]
Hey @Jackymancs4,

thanks for the pull request! I had a quick glance at it, so far it looks pretty interesting. I will try it out as soon as possible. Thanks for your efforts!

**Comment by mzdr** [comment]
Will be fixed in upcoming release as the Electron team fixed this.
