### ISSUE TITLE
Add Google-Calendar support!!

### ISSUE THREAD

**Issue by joelbandi** [mzdr/timestamp#20]
It would be amazing to get access to google calendar events and a small popup form to add them too. :) I would love to help too. Is there a recommended way to get started?
ps: I love this utility ❤️

**Comment by joelbandi** [comment]
or use applescript to get access to it from iCal?

**Comment by mzdr** [comment]
Hey Joel!

Thanks for your support and request! 👍 Unfortunately I have to disappoint you as your requested feature is way beyond the scope of this little app. I’m not aiming for building a copy of [Fantastical](https://flexibits.com/fantastical) or something similar. Maybe you’ll be happier with that? 😅 

Nevertheless I restarted working on v1.1.0 which will come with a little neat feature that opens the Apple Calendar app if you click on a date. If that’s enough all you’ve gotta have is a little patience.
