### ISSUE TITLE
 does not update time at time zone change

### ISSUE THREAD

**Issue by iiooiio** [mzdr/timestamp#21]
Amazing app. love the calendar feature.

I just found it does not update time when you move over time zones.
<img width="1040" alt="screen shot 2017-06-11 at 1 06 20 am" src="https://user-images.githubusercontent.com/6881915/27008804-41b4b09e-4e42-11e7-9054-7dff2526210d.png">

**Comment by mzdr** [comment]
Hey @iiooiio!

Thanks for bringing this to my attention. I will have a look at it!
