### ISSUE TITLE
Auto-swtiching timezones

### ISSUE THREAD

**Issue by gkatsev** [mzdr/timestamp#29]
Hi, love this app and use it daily.
Recently, I was on a trip to another timezone and for a bit was confused because Timestamp was still showing me EDT instead of PDT. There didn't seem to be a good way to update it. Eventually, I thought about restarting the app and that worked.
Would be nice if Timestamp could detect the timezone change and update accordingly (or ask the user whether to update).

**Comment by myspivey** [comment]
I have this same issue often

**Comment by mzdr** [comment]
This should be fixed in 1.1.0. Release will be soon. Please test and report if this bug is still there.
