### ISSUE TITLE
Secondary monitor calendar display issue

### ISSUE THREAD

**Issue by razvan-tudosa** [mzdr/timestamp#9]
On secondary monitor the calendar is displayed lower that normal.
See [this](https://photos.google.com/share/AF1QipNM4SnxTMteE4pUxZYdrWT4xDi0cc5J9QVMbCLk3xyZP03UCkJcX0TvXysq0LojUw?key=SEwyOGd1MmhHNFlvbG1CSF9fS2lRcUpkUEhxRjh3) photo.

**Comment by mzdr** [comment]
Thanks for reporting! I'll have a look at it!
